export const DEMO_TAGS = [
  { slug: "travel", label: "Travel", emoji: "✈️", category: "lifestyle" },
  { slug: "wine", label: "Wine", emoji: "🍷", category: "lifestyle" },
  { slug: "dinner-dates", label: "Dinner dates", emoji: "🍽️", category: "dating" },
  { slug: "city-lights", label: "City lights", emoji: "🌃", category: "lifestyle" },
  { slug: "music", label: "Music", emoji: "🎵", category: "interest" },
  { slug: "wellness", label: "Wellness", emoji: "🧘", category: "wellbeing" },
  { slug: "outdoors", label: "Outdoors", emoji: "🥾", category: "lifestyle" },
  { slug: "cocktails", label: "Cocktails", emoji: "🍸", category: "dating" },
  { slug: "romance", label: "Romance", emoji: "💖", category: "dating" },
  { slug: "nightlife", label: "Nightlife", emoji: "🎉", category: "dating" },
  { slug: "art", label: "Art", emoji: "🎨", category: "culture" },
  { slug: "fashion", label: "Fashion", emoji: "👗", category: "style" },
  { slug: "foodie", label: "Foodie", emoji: "🍜", category: "lifestyle" },
  { slug: "photography", label: "Photography", emoji: "📸", category: "creative" },
];

export const DEMO_PROFILES = [
  {
    id: "demo-profile-ava",
    username: "ava_njeri",
    display_name: "Ava Njeri",
    age: 28,
    gender: "woman",
    bio: "Sunset dinners, live music and slow weekends in the city. I love memorable conversation and easy chemistry.",
    location_area: "Westlands",
    location_label: "Westlands, Nairobi",
    location_precision: "approximate",
    is_featured: true,
    popularity_score: 96,
    view_count: 1840,
    last_active_at: new Date(Date.now() - 1000 * 60 * 13).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    relationship_goal: "dating",
    seeking: ["dating", "casual"],
    photos: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=900&q=80",
    ],
    tags: ["travel", "dinner-dates", "music", "romance"],
  },
  {
    id: "demo-profile-jamal",
    username: "jamal_kilimani",
    display_name: "Jamal K",
    age: 31,
    gender: "man",
    bio: "Weekend explorer who knows the best rooftops, hidden lounges and quiet dinner spots around town.",
    location_area: "Kilimani",
    location_label: "Kilimani, Nairobi",
    location_precision: "approximate",
    is_featured: true,
    popularity_score: 91,
    view_count: 1530,
    last_active_at: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    relationship_goal: "long-term",
    seeking: ["dating", "long-term"],
    photos: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
    ],
    tags: ["wine", "cocktails", "nightlife", "foodie"],
  },
  {
    id: "demo-profile-zoe",
    username: "zoe_parklands",
    display_name: "Zoe Park",
    age: 26,
    gender: "woman",
    bio: "Creative soul with a soft spot for art spaces, late brunches and genuine chemistry.",
    location_area: "Parklands",
    location_label: "Parklands, Nairobi",
    location_precision: "approximate",
    is_featured: false,
    popularity_score: 84,
    view_count: 1260,
    last_active_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    relationship_goal: "casual",
    seeking: ["casual", "friendship"],
    photos: [
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
    ],
    tags: ["art", "photography", "fashion", "romance"],
  },
  {
    id: "demo-profile-omar",
    username: "omar_lavington",
    display_name: "Omar L",
    age: 29,
    gender: "man",
    bio: "Easygoing, confident and always planning the next good night out with good company.",
    location_area: "Lavington",
    location_label: "Lavington, Nairobi",
    location_precision: "approximate",
    is_featured: false,
    popularity_score: 87,
    view_count: 1310,
    last_active_at: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    relationship_goal: "dating",
    seeking: ["dating", "long-term"],
    photos: [
      "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
    ],
    tags: ["nightlife", "travel", "cocktails", "dinner-dates"],
  },
  {
    id: "demo-profile-nia",
    username: "nia_karen",
    display_name: "Nia Karen",
    age: 27,
    gender: "woman",
    bio: "Nature walks, cozy dates and the kind of banter that turns into a second date instantly.",
    location_area: "Karen",
    location_label: "Karen, Nairobi",
    location_precision: "approximate",
    is_featured: true,
    popularity_score: 94,
    view_count: 1640,
    last_active_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    relationship_goal: "long-term",
    seeking: ["long-term", "dating"],
    photos: [
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
    ],
    tags: ["wellness", "outdoors", "travel", "romance"],
  },
  {
    id: "demo-profile-sami",
    username: "sami_runda",
    display_name: "Sami Runda",
    age: 30,
    gender: "non-binary",
    bio: "Big on thoughtful conversations, city adventures and warm spontaneous plans.",
    location_area: "Runda",
    location_label: "Runda, Nairobi",
    location_precision: "approximate",
    is_featured: false,
    popularity_score: 88,
    view_count: 1410,
    last_active_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
    relationship_goal: "networking",
    seeking: ["friendship", "networking"],
    photos: [
      "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
    ],
    tags: ["city-lights", "music", "foodie", "art"],
  },
];
